(()=>{"use strict";
const c=window.APP_CONFIG||{},KEY=c.TMDB_API_KEY,BASE=c.TMDB_BASE_URL||"https://api.themoviedb.org/3",IMG=c.IMAGE_BASE_URL||"https://image.tmdb.org/t/p/w500";
const $=id=>document.getElementById(id),search=$("search"),searchBtn=$("search-btn"),genres=document.querySelectorAll(".genre-btn"),recommendBtn=$("recommend-btn"),results=$("results-section"),cards=$("recommendations"),loading=$("loading"),modal=$("movie-modal"),close=$("close-modal"),modalContent=$("movie-modal-content"),sort=$("sort-by"),streaming=$("streaming-section");
let selected=[],current=[],lastFocus=null;

function esc(v){return String(v??"").replace(/&/g,"&amp;").replace(/</g,"&lt;").replace(/>/g,"&gt;").replace(/"/g,"&quot;").replace(/'/g,"&#039;")}
function poster(p){return p?IMG+p:"assets/no-poster.svg"}
function title(x){return x?.title||x?.name||"Untitled"}
function year(x){return (x?.release_date||x?.first_air_date||"").slice(0,4)||"N/A"}
function rating(x){return Number.isFinite(Number(x?.vote_average))?Number(x.vote_average).toFixed(1):"N/A"}
function busy(v){loading.classList.toggle("hidden",!v)}
function message(t,error=false){cards.innerHTML=`<div class="status-message ${error?"error":""}">${esc(t)}</div>`;results.classList.remove("hidden")}
async function api(path,params={}){if(!KEY||KEY==="YOUR_TMDB_API_KEY")throw Error("TMDB API key is missing.");const u=new URL(BASE+path);u.searchParams.set("api_key",KEY);Object.entries(params).forEach(([k,v])=>{if(v!==undefined&&v!==null&&v!=="")u.searchParams.set(k,v)});const r=await fetch(u,{headers:{Accept:"application/json"}});if(!r.ok){let m=`TMDB request failed (${r.status})`;try{const e=await r.json();if(e.status_message)m=e.status_message}catch{}throw Error(m)}return r.json()}

async function searchMovies(){const q=search.value.trim();if(!q)return message("Type a movie or series name first.");busy(true);try{const d=await api("/search/multi",{query:q,include_adult:"false",language:"en-US"});current=(d.results||[]).filter(x=>x.media_type==="movie"||x.media_type==="tv");current.length?sortMovies():message("No results found. Try another search.")}catch(e){console.error(e);message("Could not load search results. Please check the API key or try again.",true)}finally{busy(false)}}

async function recommend(){busy(true);try{if(!selected.length){const d=await api("/trending/all/week");current=(d.results||[]).filter(x=>x.media_type==="movie"||x.media_type==="tv")}else{const [m,t]=await Promise.all([api("/discover/movie",{with_genres:selected.join(","),sort_by:"vote_average.desc","vote_count.gte":"100",include_adult:"false",language:"en-US"}),api("/discover/tv",{with_genres:selected.join(","),sort_by:"vote_average.desc","vote_count.gte":"100",language:"en-US"})]);current=[...(m.results||[]).map(x=>({...x,media_type:"movie"})),...(t.results||[]).map(x=>({...x,media_type:"tv"}))]}current.length?sortMovies():message("No recommendations found.")}catch(e){console.error(e);message("Could not load recommendations. Please try again.",true)}finally{busy(false)}}

function sortMovies(){const a=[...current];if(sort.value==="rating")a.sort((x,y)=>(y.vote_average||0)-(x.vote_average||0));else if(sort.value==="newest")a.sort((x,y)=>new Date(y.release_date||y.first_air_date||0)-new Date(x.release_date||x.first_air_date||0));else a.sort((x,y)=>(y.popularity||0)-(x.popularity||0));render(a.slice(0,12))}
function render(items){cards.replaceChildren();if(!items.length)return message("No results found.");const f=document.createDocumentFragment();items.forEach(x=>f.appendChild(card(x)));cards.appendChild(f);results.classList.remove("hidden")}
function card(x){const t=title(x),el=document.createElement("article");el.className="movie-card";el.tabIndex=0;el.setAttribute("role","button");el.setAttribute("aria-label",`View details for ${t}`);el.innerHTML=`<div class="poster-wrap"><img src="${esc(poster(x.poster_path))}" alt="${esc(t)} poster" loading="lazy" onerror="this.onerror=null;this.src='assets/no-poster.svg'"><span class="rating-badge">${esc(rating(x))}</span></div><div class="movie-info"><h3>${esc(t)}</h3><div class="movie-meta">${esc(year(x))} · ${x.media_type==="tv"?"Series":"Movie"}</div></div>`;const open=()=>details(x.id,x.media_type||"movie");el.onclick=open;el.onkeydown=e=>{if(e.key==="Enter"||e.key===" "){e.preventDefault();open()}};return el}
function section(t){const group=document.createElement("section");group.className="stream-group";group.innerHTML=`<h3 class="stream-title">${esc(t)}<span>View picks</span></h3><div class="stream-list"></div>`;return group}
function streamCard(x,type,platform){const t=title(x),el=document.createElement("article");el.className="stream-card";el.tabIndex=0;el.setAttribute("role","button");el.setAttribute("aria-label",`View details for ${t}`);el.innerHTML=`<img src="${esc(poster(x.poster_path))}" alt="${esc(t)} poster" loading="lazy" onerror="this.onerror=null;this.src='assets/no-poster.svg'"><div class="stream-copy"><h3>${esc(t)}</h3><p>${esc(year(x))} · ${esc(platform)}</p></div><span class="stream-rating">★ ${esc(rating(x))}</span>`;const open=()=>details(x.id,type);el.onclick=open;el.onkeydown=e=>{if(e.key==="Enter"||e.key===" "){e.preventDefault();open()}};return el}
async function loadStreaming(){streaming.innerHTML='<p class="text-gray-400">Loading streaming & Indian picks...</p>';try{const[n,p,i]=await Promise.all([api("/discover/tv",{with_watch_providers:"8",watch_region:"IN",sort_by:"popularity.desc",language:"en-US"}),api("/discover/tv",{with_watch_providers:"119",watch_region:"IN",sort_by:"popularity.desc",language:"en-US"}),api("/discover/movie",{region:"IN",with_original_language:"hi",sort_by:"popularity.desc",language:"en-US"})]);streaming.replaceChildren();const add=(t,d,type,p)=>{if(!d.results?.length)return;const g=section(t),list=g.querySelector(".stream-list");d.results.slice(0,4).forEach(x=>list.appendChild(streamCard(x,type,p)));streaming.appendChild(g)};add("Netflix trending",n,"tv","Netflix");add("Prime Video series",p,"tv","Prime Video");add("Indian cinema",i,"movie","Indian Cinema");if(!streaming.children.length)streaming.innerHTML='<p class="status-message">No content found currently.</p>'}catch(e){console.error(e);streaming.innerHTML='<p class="text-red-400">Failed to load streaming & Indian picks.</p>'}}

async function details(id,type){busy(true);try{const d=await api(`/${type}/${encodeURIComponent(id)}`,{append_to_response:"credits,videos,watch/providers",language:"en-US"}),t=title(d),tr=d.videos?.results?.find(v=>v.type==="Trailer"&&v.site==="YouTube"&&v.key),prov=d["watch/providers"]?.results?.IN,providers=[...(prov?.flatrate||[]),...(prov?.rent||[]),...(prov?.buy||[])],unique=[...new Map(providers.map(p=>[p.provider_id,p])).values()],director=d.credits?.crew?.find(p=>p.job==="Director")?.name||"",runtime=d.runtime?`${d.runtime} min`:d.episode_run_time?.[0]?`${d.episode_run_time[0]} min/episode`:"N/A";modalContent.innerHTML=`<div class="modal-layout"><div><img src="${esc(poster(d.poster_path))}" alt="${esc(t)} poster" class="modal-poster" onerror="this.onerror=null;this.src='assets/no-poster.svg'"></div><div><h2 id="modal-title">${esc(t)}</h2><div class="modal-meta"><span>★ ${esc(rating(d))}</span><span>${esc(runtime)}</span><span>${esc(year(d))}</span><span>${esc(d.genres?.map(g=>g.name).join(" · ")||"Unknown")}</span></div>${unique.length?`<h3>Available in India</h3><p>${esc(unique.map(p=>p.provider_name).join(", "))}</p>`:""}<h3>Overview</h3><p>${esc(d.overview||"No overview available.")}</p>${director?`<h3>Director</h3><p>${esc(director)}</p>`:""}${tr?`<h3>Trailer</h3><div class="trailer-frame"><iframe src="https://www.youtube.com/embed/${encodeURIComponent(tr.key)}" title="${esc(t)} trailer" loading="lazy" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture; web-share" allowfullscreen></iframe></div>`:""}</div></div>`;lastFocus=document.activeElement;modal.classList.remove("hidden");document.body.classList.add("overflow-hidden");close.focus()}catch(e){console.error(e);modalContent.innerHTML=`<div class="text-center py-10"><p class="text-red-400">Failed to load details.</p><p class="text-gray-400 text-sm">${esc(e.message)}</p></div>`;lastFocus=document.activeElement;modal.classList.remove("hidden");close.focus()}finally{busy(false)}}
function closeModal(){modal.classList.add("hidden");document.body.classList.remove("overflow-hidden");if(lastFocus?.focus)lastFocus.focus()}

genres.forEach(b=>{b.setAttribute("aria-pressed","false");b.onclick=()=>{const g=b.dataset.genre;if(selected.includes(g)){selected=selected.filter(x=>x!==g);b.classList.remove("active");b.setAttribute("aria-pressed","false")}else{selected.push(g);b.classList.add("active");b.setAttribute("aria-pressed","true")}}});
searchBtn.onclick=searchMovies;search.onkeydown=e=>{if(e.key==="Enter")searchMovies()};recommendBtn.onclick=recommend;sort.onchange=()=>current.length&&sortMovies();close.onclick=closeModal;modal.onclick=e=>e.target===modal&&closeModal();document.onkeydown=e=>{if(e.key==="Escape"&&!modal.classList.contains("hidden"))closeModal();if(e.key==="/"&&document.activeElement?.tagName!=="INPUT"){e.preventDefault();search.focus()}};window.addEventListener("load",async()=>{if(window.AOS)AOS.init({once:true,offset:35,duration:600,easing:"ease-out-cubic"});try{const h=await api("/trending/movie/day");const b=h.results?.find(x=>x.backdrop_path)?.backdrop_path;if(b)document.getElementById("hero-bg").style.backgroundImage=`url(https://image.tmdb.org/t/p/original${b})`}catch(e){}recommend();loadStreaming()});
})();